### ISSUE TITLE
Add Excel spreadsheets to releases

### ISSUE THREAD

**Issue by dmey** [psychrometrics/psychrolib#15]
Specifically for VBA/Excel, I think it would be a good idea to add the ready-made spreadsheets (i.e. with PsychroLib already included) for the IP and SI version to the [releases](https://github.com/psychrometrics/psychrolib/releases) so that users who want to make use of PsychroLib in Excel can simply download the spreadsheet instead of having to download the repo and add the VBA script manually. @didierthevenard what do you think?

**Comment by didierthevenard** [comment]
Would definitely make things simpler, although it may raise flags for some users because macro-enabled Excel workbooks are disabled by default. Let me think about it.

**Comment by dmey** [comment]
They would have to enable macros manually but they are prompted automatically as soon as the file is open and should make it more straightforward than having to add them to the VBA editor manually.
![image](https://user-images.githubusercontent.com/26348635/51601232-b8595e80-1efb-11e9-81ed-638c32bab47d.png)

**Comment by dmey** [comment]
Closing as it will be included as part of #18.
