### ISSUE TITLE
Document how to run VBA tests in Excel

### ISSUE THREAD

**Issue by dmey** [psychrometrics/psychrolib#19]
@didierthevenard I am not entirely sure how to run the tests in Excel -- could you add a how to in CONTRIBUTING.md when you have time?

**Comment by didierthevenard** [comment]
This is probably outside of the scope of PsychroLib. But in essence go in the VBA editor, click on RunAllTests, then press on the Run icon or select the Run/Run menu. Results will appear in the Immediate window at the bottom of the screen.

**Comment by dmey** [comment]
Perfect thanks -- I had the 'Immediate window' disabled, hence I could not see any outputs. 
Will add this to the testing section in [CONTRIBUTING.md](https://github.com/psychrometrics/psychrolib/blob/master/CONTRIBUTING.md#testing) as we have done for the python testing so it's clear for us or anyone wanting to contribute.
