### ISSUE TITLE
How to calcuate psychrometric properties in Excel with PsychroLib

### ISSUE THREAD

**Issue by jakkalavanya1** [psychrometrics/psychrolib#43]
I am trying to use this in the excel sheet. I am unable to use your PsychroLib_2.2.2_SI macro-enabled excel worksheet as it is in a protected view. I downloaded it from releases.
https://github.com/psychrometrics/psychrolib/releases
I have tried to 'enable all macos', also tried to uncheck 'Enable protected view for files originating from the internet' But still, I can't see anything in the excel sheets.
Can you tell me how to open this?

**Comment by dmey** [comment]
There is an [Excel section in the how to use PsychroLib guide](https://github.com/psychrometrics/psychrolib/blob/master/docs/examples.md#microsoft-excel-visual-basic-for-applications-vba) -- please can you let me know if this is unclear? You can call any functions directly from cells like when you call any other functions. For a list of available function in PsychroLib please see the [Overview page] (https://github.com/psychrometrics/psychrolib/blob/master/docs/overview.md#available-functions) or the [API docs](https://psychrometrics.github.io/psychrolib/api_docs.html). Please note that the `Const PSYCHROLIB_UNITS = UnitSystem.{SI, IP}` has already been set for you if you download the SI or IP releases. Let me know if something is not clear and I will clarify in the docs!

**Comment by dmey** [comment]
@jakkalavanya1 did the above help?

**Comment by jakkalavanya1** [comment]
> @jakkalavanya1 did the above help?

Thank you so much. It is clear in the documentation. I got it working. Appreciate your quick response.
