### ISSUE TITLE
GetTDryBulb

### ISSUE THREAD

**Issue by birdol** [psychrometrics/psychrolib#46]
sometimes need

Get TDryBulb From WetBuld and RH，or WB and HumRatio，or RH and HumRatio

even  MoistAirEnthalpy and HumRatio

**Comment by dmey** [comment]
I do not understand your question -- please state clearly your issue by completing the pre-filled guideline. If you are requesting a new feature, please click and fill in a feature request.

![image](https://user-images.githubusercontent.com/26348635/68596057-7ef5dd80-0492-11ea-96d1-e168b2ab9520.png)

**Comment by birdol** [comment]
sorry for my poor English。

I want to calculate the dry bulb temperature by the wet bulb temperature and the relative humidity, or the dry bulb temperature by the wet bulb temperature and the HumRatio, or the dry bulb temperature by the relative humidity and the HumRatio.


like  TDryBulb=function(Twet, RelHum，Press)  and so on。

**Comment by didierthevenard** [comment]
Thanks for the clarification. It is true that most functions in the library assume that dry bulb temperature is known, and compute one moisture-related variable (such as wet bulb temperature, relative humidity, humidity ratio, etc.) from another. What is your application, that is, what is the reason for you to calculate dry bulb temperature from other variables?

**Comment by dmey** [comment]
I am closing this now as no response from user.
