### ISSUE TITLE
Reduce CI runtime for R

### ISSUE THREAD

**Issue by dmey** [psychrometrics/psychrolib#55]
At the moment most of the time spent in CI is due to R (building dependencies). @hongyuanjia do you know if we can use pre-compiled binaries? Or do you know of other ways to considerably reduce the build time for the R version?

**Comment by hongyuanjia** [comment]
Lots of time have been spent to install devtools package (around 10mins), which depends lots of other packages directly and indirectly. One possible solution I think will be using RStudio Package Manager which provides pre-compiled binaries for some Linux systems. Example: https://github.com/tidyverse/dplyr/blob/f4a39dcaf5058e9412ef1cbd909bcdb82a66519b/.github/workflows/R-CMD-check.yaml#L24

I will send a PR on this later

**Comment by hongyuanjia** [comment]
With #58, the total runtime of CI for R is about 8 mins. Not super fast, but is much faster than the original time 14mins.

I have no idea why RSPM does not work on travis. The speed was mainly gained by reducing package sizes to install and removing package code coverage checking.

**Comment by dmey** [comment]
Thanks for this! I think that this is good enough -- not really worth spending a lot of time on this.
