### ISSUE TITLE
installing this package can't complete

### ISSUE THREAD

**Issue by thomasswf** [psychrometrics/psychrolib#65]
hi is there anyone could help with?
if i run the following code:
```
from distutils.core import setup

setup(name='PsychroLib',
      version='2.5.0',
      maintainer = 'The PsychroLib Developers',
      description='Library of psychrometric functions to calculate thermodynamic properties of air',
      author='D. Thevenard and D. Meyer',
      author_email='didierthevenard@users.noreply.github.com',
      url='https://github.com/psychrometrics/psychrolib',
      license='MIT',
      platforms = ['Windows', 'Linux', 'Solaris', 'Mac OS-X', 'Unix'],
      python_requires='>=3.6',
      py_modules=['psychrolib'],
     )
```
----------------------------------------------
i got the following:
----------------------------------------------
```
/anaconda3/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)

An exception has occurred, use %tb to see the full traceback.

SystemExit: usage: ipykernel_launcher.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: ipykernel_launcher.py --help [cmd1 cmd2 ...]
   or: ipykernel_launcher.py --help-commands
   or: ipykernel_launcher.py cmd --help

error: option -f not recognized


/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3304: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)
```

**Comment by dmey** [comment]
What are you trying to do?

**Comment by thomasswf** [comment]
> What are you trying to do?

i want to install this package"PsychroLib" but no luck.


i am using anaconda on MacOS

**Comment by dmey** [comment]
```
pip install PsychroLib
```

**Comment by thomasswf** [comment]
thanks dmey. helps alot. that's interesting, it is suddenly working after i have updated all the packages in anaconda.
i tried that before it worked but couldn't import after install. now it works after you ask me to try pip.

powerful

**Comment by thomasswf** [comment]
not working, trying to downversion cffi
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-91-2be95b173347> in <module>
      2 # Set the unit system, for example to SI (can be either psychrolib.SI or psychrolib.IP)
      3 psy.SetUnitSystem(psychrolib.SI)
----> 4 TDewPoint = psy.GetTDewPointFromRelHum(25.0, 0.80)
      5 print(TDewPoint)

/anaconda3/lib/python3.7/site-packages/numba/np/ufunc/dufunc.py in _compile_for_args(self, *args, **kws)
    191                 argty = numpy_support.map_arrayscalar_type(arg)
    192             argtys.append(argty)
--> 193         return self._compile_for_argtys(tuple(argtys))
    194 
    195     def _compile_for_argtys(self, argtys, return_type=None):

/anaconda3/lib/python3.7/site-packages/numba/np/ufunc/dufunc.py in _compile_for_argtys(self, argtys, return_type)
    209             sig = return_type(*argtys)
    210         cres, argtys, return_type = ufuncbuilder._compile_element_wise_function(
--> 211             self._dispatcher, self.targetoptions, sig)
    212         actual_sig = ufuncbuilder._finalize_ufunc_signature(
    213             cres, argtys, return_type)

/anaconda3/lib/python3.7/site-packages/numba/np/ufunc/ufuncbuilder.py in _compile_element_wise_function(nb_func, targetoptions, sig)
    141     # Do compilation
    142     # Return CompileResult to test
--> 143     cres = nb_func.compile(sig, **targetoptions)
    144     args, return_type = sigutils.normalize_signature(sig)
    145     return cres, args, return_type

/anaconda3/lib/python3.7/site-packages/numba/np/ufunc/ufuncbuilder.py in compile(self, sig, locals, **targetoptions)
     90         flags.unset("enable_looplift")
     91 
---> 92         return self._compile_core(sig, flags, locals)
     93 
     94     def _compile_core(self, sig, flags, locals):

/anaconda3/lib/python3.7/site-packages/numba/np/ufunc/ufuncbuilder.py in _compile_core(self, sig, flags, locals)
    125                                               self.py_func, args=args,
    126                                               return_type=return_type,
--> 127                                               flags=flags, locals=locals)
    128 
    129                 # cache lookup failed before so safe to save

/anaconda3/lib/python3.7/site-packages/numba/core/compiler.py in compile_extra(typingctx, targetctx, func, args, return_type, flags, locals, library, pipeline_class)
    565     """
    566     pipeline = pipeline_class(typingctx, targetctx, library,
--> 567                               args, return_type, flags, locals)
    568     return pipeline.compile_extra(func)
    569 

/anaconda3/lib/python3.7/site-packages/numba/core/compiler.py in __init__(self, typingctx, targetctx, library, args, return_type, flags, locals)
    286         # Make sure the environment is reloaded
    287         config.reload_config()
--> 288         typingctx.refresh()
    289         targetctx.refresh()
    290 

/anaconda3/lib/python3.7/site-packages/numba/core/typing/context.py in refresh(self)
    154         Useful for third-party extensions.
    155         """
--> 156         self.load_additional_registries()
    157         # Some extensions may have augmented the builtin registry
    158         self._load_builtins()

/anaconda3/lib/python3.7/site-packages/numba/core/typing/context.py in load_additional_registries(self)
    679 
    680     def load_additional_registries(self):
--> 681         from . import (
    682             cffi_utils,
    683             cmathdecl,

/anaconda3/lib/python3.7/site-packages/numba/core/typing/cffi_utils.py in <module>
     17 try:
     18     import cffi
---> 19     ffi = cffi.FFI()
     20 except ImportError:
     21     ffi = None

/anaconda3/lib/python3.7/site-packages/cffi/api.py in __init__(self, backend)
     54                     raise Exception("Version mismatch: this is the 'cffi' package version %s, located in %r.  When we import the top-level '_cffi_backend' extension module, we get version %s, located in %r.  The two versions should be equal; check your installation." % (
     55                         __version__, __file__,
---> 56                         backend.__version__, backend.__file__))
     57                 else:
     58                     # PyPy

Exception: Version mismatch: this is the 'cffi' package version 1.12.2, located in '/anaconda3/lib/python3.7/site-packages/cffi/api.py'.  When we import the top-level '_cffi_backend' extension module, we get version 1.14.0, located in '/anaconda3/lib/python3.7/site-packages/_cffi_backend.cpython-37m-darwin.so'.  The two versions should be equal; check your installation.

**Comment by thomasswf** [comment]
this package now is working with down version the cffi package to 1.12.2.


> Exception: Version mismatch: this is the 'cffi' package version 1.12.2, located in '/anaconda3/lib/python3.7/site-packages/cffi/api.py'. When we import the top-level '_cffi_backend' extension module, we get version 1.14.0, located in '/anaconda3/lib/python3.7/site-packages/_cffi_backend.cpython-37m-darwin.so'. The two versions should be equal; check your installation.

**Comment by dmey** [comment]
@thomasswf I do not quite understand what you mean -- PsychroLib does not have a dependency on CFFI. Only for testing we use CFFI and have a dependency on it but you do not need it. I have tested on conda using a minimal example (below) but could not find any issues. Could you also try?

```
conda create -n test-psy python=3.7
conda activate test-psy
pip install psychrolib --no-cache-dir
```
