### ISSUE TITLE
Documentation of magic numbers

### ISSUE THREAD

**Issue by C-H-Simpson** [psychrometrics/psychrolib#67]
I'm frustrated by the fact that constants are included in the calculations with no documentation of what they mean. For example
```
HumRatio = ((2501. - 2.326 * TWetBulb) * Wsstar - 1.006 * (TDryBulb - TWetBulb)) \
                    / (2501. + 1.86 * TDryBulb - 4.186 * TWetBulb)
```

This makes it harder to compare the methods used to other methods, or to describe in words the method that is being used; for example in the 'methods' section of an academic publication.
The cited sources for the equations in psychrolib are behind a paywall. My institution does not have access to the ASHRAE handbook, and the price of it is rather steep.
This definitely makes me less likely to use this package in my work.

**Comment by C-H-Simpson** [comment]
Actually, I'll close this as it overlaps with issue #16

**Comment by dmey** [comment]
This is something we should address in #16 however it would not cover all coefficients as some where empirically derived.

**Comment by C-H-Simpson** [comment]
Provided #16 is done, I think it would be fine to just identify in the docstrings (or other comments) that empirically derived coefficients are used.
