### ISSUE TITLE
Get a runtime warning when using plot function

### ISSUE THREAD

**Issue by Jiiilllll** [psychrometrics/psychrolib#77]
Hi, I tried this library with some examples in the notebook.

It shows this error when I use the plot function " RuntimeWarning: divide by zero encountered in GetRelHumFromTWetBulb
  GetSatVapPres(db_t) * GetRelHumFromTWetBulb(db_t, wb_t, p_atm),"

Please advise the way to get rid of this error. Many thanks!

**Comment by dmey** [comment]
Can you please fill in a detailed bug report so that I can try to reproduce it at my end? Language and version number, PshcyroLib version, OS, code snippet with steps and inputs you call, etc...

**Comment by dmey** [comment]
closing as no response from the user.
