### ISSUE TITLE
Example of js psychrometric chart

### ISSUE THREAD

**Issue by chemlabros** [psychrometrics/psychrolib#78]
**Is your feature request related to a problem? Please describe.**
Demo of psychrolib.js to create a JS psychrometric chart based on altitude and values returned by psychrolib.js library. 

**Describe the solution you'd like**
Made this [gist](https://gist.github.com/chemlabros/2c3dcda914cfb5c47690dce06b30e2af#file-psychrolib_test_js-html) as a demo of the JS implementation of your psychrolib. I've used chart.js as a charting library which is also MIT licensed. 
Implement my code if you wish as a demo html file in your library for JS under MIT license. 

**Describe alternatives you've considered**
One great solution is use also MIT licensed two.js to draw the graph instead of chart.js that I used, in order to display labels and limit the graph or display comfort zones which cannot be done in chart.js without plugins. 

**Additional context**

**Comment by dmey** [comment]
Thanks but I am not sure where we could put this. If you were thinking about contributing to the library, I think it would be interesting to create one to compute psychro functions based on the js functions provided (something like https://www.kwangu.com/work/psychrometric.htm or https://www.sugartech.co.za/psychro/index.php). Is this something you'd be interested in doing?

**Comment by chemlabros** [comment]
A reconstruction of the paychrometric chart is what I did using loops and your library as a base point. 
This is just an exaple. So no issue there. Closing it.
