### ISSUE TITLE
GetTDewPointFromTWetBulb error?

### ISSUE THREAD

**Issue by Syloreon** [psychrometrics/psychrolib#81]
**Describe the bug**
I'm using the following in python
psy.SetUnitSystem(psy.IP)
psy.GetTDewPointFromTWetBulb(100, 40, 12.23) and the answer is -126.65009138804012

**To Reproduce**
1. Open Python
2. psy.SetUnitSystem(psy.IP)
3. psy.GetTDewPointFromTWetBulb(100, 40, 12.23)
4. -126.65009138804012

**Expected behavior**
The dew point at 100Fdb and 40Fwb at 12.23 psi barometric pressure would not give a negative dew point.

**Screenshots**
![image](https://user-images.githubusercontent.com/79756576/125167212-05c9f480-e165-11eb-90b8-ead305b593a5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 91.0.4472.124 (Official Build) (64-bit)

**Comment by dmey** [comment]
Pressure needs to be in Pa

**Comment by Syloreon** [comment]
Hello
The documentation indicates IP would be in psi.
Is the documentation incorrect?


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by dmey** [comment]
Sorry -- yes let me check again actually misread your issue thought this was SI.

**Comment by Syloreon** [comment]
Hello very sorry, I entered in values that would generate an error.
I just checked against https://sugartech.co.za/psychro/index.php
It would be better to have it kick back a null value instead of a value to avoid someone using the data.
Thanks.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by dmey** [comment]
no problems and good point thanks -- we do have checks but this has clearly gone unnoticed. I'll mark this as a TODO for the next release bit cannot guarantee you when it will be fixed right now.

**Comment by Syloreon** [comment]
Thanks no worries on my end. I’m working with actual data so not likely to get wrong inputs.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
