### ISSUE TITLE
Test Building of C# failing

### ISSUE THREAD

**Issue by DJGosnell** [psychrometrics/psychrolib#83]
Since commit 99bf2479e8f3c20c1a06d9a55789f37ed6a883cc, the test suite for C# is failing.  Currently researching why the c_sharp test is failing.  I'll hopefully have some reason/solution by tomorrow.

May be related to #76

**Comment by dmey** [comment]
thanks -- https://app.travis-ci.com/github/psychrometrics/psychrolib/jobs/546351173 seems to be due to https://github.com/dotnet/core/issues/4446

**Comment by dmey** [comment]
Closed via #84.
