### ISSUE TITLE
Psychometric chart question

### ISSUE THREAD

**Issue by Atantuccio** [psychrometrics/psychrolib#87]
I'm a relatively new Python user, so I am a bit unfamiliar with the navigation and syntax. However, is there a way to input a minimum set of parameters which close the solution to the function and list out the remaining values at that point on the chart?

**Comment by didierthevenard** [comment]
I believe that functions CalcPsychrometricsFromTWetBulb, CalcPsychrometricsFromTDewPoint, or CalcPsychrometricsFromRelHum, described in https://github.com/psychrometrics/psychrolib/blob/master/docs/overview.md may be what you are looking for.

**Comment by dmey** [comment]
@Atantuccio sorry but don't quite understand the question but if you are looking to make psychrometric charts in Python, check out the excellent https://github.com/azogue/psychrochart which relies on PsychroLib for psychrometric  calculations.

**Comment by Atantuccio** [comment]
Thanks, I’ve checked it out and made some of the charts… they look great. I was more interested in using the library as a function to determine the certain parameters such as dew point, wet bulb, or RH by specifying 2 or 3 input parameters, such that there are no remaining degrees of freedom.

Best Regards,

Anthony

**Comment by Atantuccio** [comment]
Yes! That’s it. For some reason I could not find that documentation.

Best regards,

Anthony

**Comment by dmey** [comment]
I am closing this down as solved in #88. Please see https://psychrometrics.github.io/psychrolib/api_docs.html for docs.
